version: 2
updates:
  # Enable version updates for Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "wdecoster"
    assignees:
      - "wdecoster"
    commit-message:
      prefix: "cargo"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "wdecoster"
    assignees:
      - "wdecoster"
    commit-message:
      prefix: "ci"
      include: "scope"
